[[LibModbus]]
arch = "aarch64"
git-tree-sha1 = "0ccc1080eb777e0a660bf65b6a7b905b2b8aa5f4"
libc = "glibc"
os = "linux"

    [[LibModbus.download]]
    sha256 = "a0c221d6e7845a25a1f7dda52c945245fe9bc47537af4238d7410dcd68a74a75"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.aarch64-linux-gnu.tar.gz"
[[LibModbus]]
arch = "aarch64"
git-tree-sha1 = "bcc4dbef8727f02f5a2997a44ec1c5975f37e70a"
libc = "musl"
os = "linux"

    [[LibModbus.download]]
    sha256 = "a1ec6151f39a51eb15ef93d29d10a2d24bd1beb05c2a7df3d6bcfdbf26afe9bd"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.aarch64-linux-musl.tar.gz"
[[LibModbus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6ed374865cb71e45ae54f292e34bed3728c5123"
libc = "glibc"
os = "linux"

    [[LibModbus.download]]
    sha256 = "25c484f5253f0dda823d50e32257ba466adc3b3db3eeb9c1042eb67d64f9f974"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[LibModbus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad150ff21da31321bf26ad8907d9158d8cc682e1"
libc = "musl"
os = "linux"

    [[LibModbus.download]]
    sha256 = "214a419f7ce3b50800b898857ac7015a291a59098562cea211ae2051daa08754"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[LibModbus]]
arch = "i686"
git-tree-sha1 = "ece3532da9c3b3f4b0f0d1bfcdd7356e7372f761"
libc = "glibc"
os = "linux"

    [[LibModbus.download]]
    sha256 = "6f12a840f4415d71a12545d9060972208fe1a2e22ab8c91025af8d4d31fb1ecc"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.i686-linux-gnu.tar.gz"
[[LibModbus]]
arch = "i686"
git-tree-sha1 = "b82ff971792aa9b238e12f467ca9c1517f64873b"
libc = "musl"
os = "linux"

    [[LibModbus.download]]
    sha256 = "a9e56659c9f7b0ff3103e61500da14d93f9968a0bf05b4e20a5637d911f01128"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.i686-linux-musl.tar.gz"
[[LibModbus]]
arch = "i686"
git-tree-sha1 = "79bad3e41e8a6383ca1decbe51849533c975c893"
os = "windows"

    [[LibModbus.download]]
    sha256 = "7d7a3d6b8fb30c407ed9028f86406c7cbdb7220be14140ce967822c4d20316b3"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.i686-w64-mingw32.tar.gz"
[[LibModbus]]
arch = "powerpc64le"
git-tree-sha1 = "e294f2ee0a643346783c84791f138b37562038e2"
libc = "glibc"
os = "linux"

    [[LibModbus.download]]
    sha256 = "d46d2fdcbd48ad1b926915483aadf8220aa90cb7a4a18ff5e879f33b6587d54c"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[LibModbus]]
arch = "x86_64"
git-tree-sha1 = "9f18f389d3eb2d477be0279990bf9a24c0211e28"
os = "macos"

    [[LibModbus.download]]
    sha256 = "b5351196366ecbd3739af59bad3757c8ed5221c0212a036e9a2bf088df3c5d23"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.x86_64-apple-darwin.tar.gz"
[[LibModbus]]
arch = "x86_64"
git-tree-sha1 = "e0bebfed4bc80215e6e91a97bd49aa703967657e"
libc = "glibc"
os = "linux"

    [[LibModbus.download]]
    sha256 = "af92f220cc049918cb0837f35c5e7f2f61b390f619c4cdc26ac17e4be18f09eb"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.x86_64-linux-gnu.tar.gz"
[[LibModbus]]
arch = "x86_64"
git-tree-sha1 = "403c0f03aa9ec29366a20b9e64d07f35d364df32"
libc = "musl"
os = "linux"

    [[LibModbus.download]]
    sha256 = "498c2feac4835aecdf2cd52148ba38d928a331e1fe83bb0294d34cff0a193b63"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.x86_64-linux-musl.tar.gz"
[[LibModbus]]
arch = "x86_64"
git-tree-sha1 = "8485c5aa18df6b1dafb6b60925805830360cb4d5"
os = "freebsd"

    [[LibModbus.download]]
    sha256 = "ea7112c896688982c0477a1c48f021bd90a12b6a5897cf5722b939b2ecc93749"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[LibModbus]]
arch = "x86_64"
git-tree-sha1 = "e6b580314149fce13172f300f87fdd4c58fe79d7"
os = "windows"

    [[LibModbus.download]]
    sha256 = "ce9f06c1a449d29fb3a323d5f30efb4155425eab184b1e1d7370659292688ffe"
    url = "https://github.com/JuliaBinaryWrappers/LibModbus_jll.jl/releases/download/LibModbus-v0.1.0+1/LibModbus.v0.1.0.x86_64-w64-mingw32.tar.gz"
