# Autogenerated wrapper script for LibModbus_jll for x86_64-w64-mingw32
export libmodbus_so_5_1_0

JLLWrappers.@generate_wrapper_header("LibModbus")
JLLWrappers.@declare_library_product(libmodbus_so_5_1_0, "libmodbus-5.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmodbus_so_5_1_0,
        "bin\\libmodbus-5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
